apiVersion: v1
kind: Service
metadata:
  name: {{ include "node-hello.fullname" . }}
  labels:
    {{- include "node-hello.labels" . | nindent 4 }}
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    {{- include "node-hello.selectorLabels" . | nindent 4 }}
